### ISSUE TITLE
Colors Sky, Mint, Lime, Yellow and Amber are not correct

### ISSUE THREAD

**Issue by markuspfeifenberger** [radix-ui/colors#8]
Hi,

the five color are not correct. The values of the colors 7,  need to be swapped with 9, 10

Eg vor sky:

*   \--colors-sky7 should have the value of --colors-sky9
*   \--colors-sky8 should have the value of --colors-sky10
*   \--colors-sky9 should have the value of --colors-sky7
*   \--colors-sky10 should have the value of --colors-sky8

![](https://user-images.githubusercontent.com/7107293/124233585-485f5180-db13-11eb-96de-02551a226651.png)

**Comment by colmtuite** [comment]
How do you mean they're not correct? Why do they need to be swapped?

**Comment by markuspfeifenberger** [comment]
When the colors are considered to be 12 the darkest color, the value 7,8 are darken den 9,10 - if it is on purpose, please close the issue

**Comment by colmtuite** [comment]
There is no intentional lightness progression from steps `0` to `12`. Each step is designed for a specific use case, and it just works out that there's a progression in lightness.

Those 5 bright colors are designed for black foreground text at steps `9` and `10`, but the surrounding steps are still designed for borders and text. So it works out that the surrounding steps are lighter, but that's ok.
