### ISSUE TITLE
Alpha Transparency

### ISSUE THREAD

**Issue by PhilGarb** [radix-ui/colors#9]
Hey everyone,

Great work on the color system. 
I have question about the alpha variants. 
It seems like they are the same spectrum as a solid color, but I am not sure how I would best use them. 

### Expectation
My first intuition with transparency is to extend the solid color with it when I need the background to be transparent, but want to keep the same solid base color. This is how [Tailwind](https://tailwindcss.com/docs/background-opacity) does it. This gives me the ability to have all the combinations of a color and all the possible transparencies.

### Question
It seems to me that the radix alpha colors would be used differently, because the colors are picked deliberately. Could you explain the idea behind the alpha colors and how you intend for them to be used?

**Comment by colmtuite** [comment]
The idea is that the opaque and alpha scales are interchangeable, since they match almost perfectly.

Sometimes you need a color to be transparent, so it works well on coloured backgrounds for example. Let's say you have a text field with a light gray border, we'll use Mauve for this example. You use step mauve7 here for the border. That border will work well on a white background in light mode, or a dark background in dark mode.

But the border won't look great on a purple background for example. So you can use mauveA7, which is transparent. Now your text field border will work well on any background because it blends in, but it still looks the same as mauve7 on white/dark backgrounds.

Sometimes you need opaque colors, sometimes transparent. Now you have the option.

**Comment by PhilGarb** [comment]
Thank you for that explanation. That makes a lot of sense to me and sounds very helpful.

**Comment by binyamin** [comment]
@colmtuite Can you please explain this in the docs (on the website)?

**Comment by inwardmovement** [comment]
It would be great also to provide and example showing a visual comparison with/without alpha color.
